import { describe, expect, it } from 'vitest'
import { DesktopIpcId, parseDesktopIpcMessage, type DesktopIpcMessage } from '../src/index.ts'

/** A commit args object whose grant payload is cyclic: valid key surfaces, invalid JSON content. */
function cyclicGrantRecordArgs(): unknown {
  const payload: Record<string, unknown> = {}
  payload['self'] = payload
  return { key: 'a/b', lease: 'l', record: { kind: 'grant', payload } }
}

const valid: DesktopIpcMessage[] = [
  { t: 'fetch', id: DesktopIpcId('f'), url: 'http://127.0.0.1/api/x', method: 'POST', headers: {}, body: '{}' },
  { t: 'fetch', id: DesktopIpcId('fs'), url: 'http://127.0.0.1/export', method: 'GET', headers: {}, streamBody: true },
  { t: 'fetch-cancel', id: DesktopIpcId('f') },
  { t: 'fetch-pull', id: DesktopIpcId('fs') },
  { t: 'fetch-res', id: DesktopIpcId('f'), status: 200, statusText: 'OK', headers: {}, body: null, bodyBase64: 'AA==' },
  { t: 'fetch-res', id: DesktopIpcId('fs'), status: 200, statusText: 'OK', headers: {}, body: null, bodyStream: true },
  { t: 'fetch-chunk', id: DesktopIpcId('fs'), bodyBase64: 'AA==' },
  { t: 'fetch-end', id: DesktopIpcId('fs') },
  { t: 'fetch-error', id: DesktopIpcId('fs'), error: 'failed' },
  { t: 'open-stream', id: DesktopIpcId('s'), endpoint: '$events', payload: {} },
  { t: 'stream-cancel', id: DesktopIpcId('s') },
  { t: 'stream-item', id: DesktopIpcId('s'), value: null },
  { t: 'stream-end', id: DesktopIpcId('s') },
  { t: 'stream-error', id: DesktopIpcId('s'), error: { code: 'internal' } },
  {
    t: 'boot-res',
    injections: [
      { kind: 'global', name: '__BOOT__', value: {} },
      { kind: 'script', placement: 'head', text: 'globalThis.ready = true' },
      { kind: 'script-src', placement: 'body', src: '/entry.js' },
      { kind: 'script-preload', src: '/preload.js' },
      { kind: 'style', text: 'body {}' },
      { kind: 'html', placement: 'body', html: '<main></main>' },
    ],
  },
  { t: 'shutdown', code: 0 },
  { t: 'shutdown', code: 1 },
  { t: 'native-request', id: DesktopIpcId('n1'), op: 'directory-pick' },
  { t: 'native-request', id: DesktopIpcId('n2'), op: 'credential-has', args: { ref: 'DEEPSEEK_API_KEY' } },
  {
    t: 'native-request',
    id: DesktopIpcId('n3'),
    op: 'credential-set',
    args: { ref: 'DEEPSEEK_API_KEY', value: 'sk-x' },
  },
  {
    t: 'native-request',
    id: DesktopIpcId('n4'),
    op: 'credential-record-commit',
    args: { key: 'llm-pi-ai/route', lease: 'l1', record: { kind: 'grant', payload: { token: 't' } } },
  },
  { t: 'native-ok', id: DesktopIpcId('n1'), op: 'directory-pick', value: '/chosen' },
  { t: 'native-ok', id: DesktopIpcId('n1'), op: 'directory-pick', value: null },
  { t: 'native-ok', id: DesktopIpcId('n2'), op: 'credential-has', value: true },
  { t: 'native-ok', id: DesktopIpcId('n5'), op: 'credential-record-abort' },
  { t: 'native-ok', id: DesktopIpcId('n6'), op: 'credential-record-list', value: [] },
  {
    t: 'native-ok',
    id: DesktopIpcId('n7'),
    op: 'credential-record-lease',
    value: { lease: 'l2', record: null },
  },
  {
    t: 'native-request',
    id: DesktopIpcId('n8'),
    op: 'credential-set',
    args: { ref: 'X', value: 'sk-z' },
  },
  {
    t: 'native-ok',
    id: DesktopIpcId('n9'),
    op: 'credential-record-read',
    value: { kind: 'api-key', key: 'sk', env: { PROFILE: 'x' } },
  },
  {
    t: 'native-ok',
    id: DesktopIpcId('n10'),
    op: 'credential-record-list',
    value: [{ key: 'a/b', kind: 'grant' }],
  },
  {
    t: 'native-ok',
    id: DesktopIpcId('n11'),
    op: 'credential-record-status',
    value: { configured: true, kind: 'grant' },
  },
  { t: 'native-ok', id: DesktopIpcId('n12'), op: 'credential-record-status', value: { configured: true } },
  { t: 'native-ok', id: DesktopIpcId('n13'), op: 'credential-set', value: false },
  { t: 'native-ok', id: DesktopIpcId('n14'), op: 'credential-record-commit', value: { kind: 'grant', payload: [1, 'two'] } },
  {
    t: 'native-request',
    id: DesktopIpcId('n15'),
    op: 'credential-record-commit',
    args: { key: 'a/b', lease: 'l2', record: { kind: 'grant', payload: null } },
  },
  { t: 'native-request', id: DesktopIpcId('n16'), op: 'credential-get', args: { ref: 'X' } },
  { t: 'native-request', id: DesktopIpcId('n17'), op: 'credential-unset', args: { ref: 'X' } },
  { t: 'native-request', id: DesktopIpcId('n18'), op: 'credential-record-status', args: { key: 'a/b' } },
  { t: 'native-request', id: DesktopIpcId('n19'), op: 'credential-record-read', args: { key: 'a/b' } },
  { t: 'native-request', id: DesktopIpcId('n20'), op: 'credential-record-list' },
  { t: 'native-request', id: DesktopIpcId('n21'), op: 'credential-record-lease', args: { key: 'a/b' } },
  { t: 'native-request', id: DesktopIpcId('n22'), op: 'credential-record-abort', args: { lease: 'l3' } },
  { t: 'native-request', id: DesktopIpcId('n23'), op: 'credential-record-delete', args: { key: 'a/b' } },
  { t: 'native-ok', id: DesktopIpcId('n24'), op: 'credential-unset', value: true },
  { t: 'native-ok', id: DesktopIpcId('n25'), op: 'credential-record-delete', value: false },
  { t: 'native-error', id: DesktopIpcId('n1'), op: 'credential-get', error: 'unavailable' },
]

describe('desktop IPC parser', () => {
  it('accepts every carrier message', () => {
    for (const message of valid) expect(parseDesktopIpcMessage(message)).toEqual(message)
  })

  it.each([
    null,
    [],
    {},
    { t: 'unknown' },
    { t: 'boot-res', injections: null },
    { t: 'boot-res', injections: [null] },
    { t: 'boot-res', injections: [{ kind: 1 }] },
    { t: 'boot-res', injections: [{ kind: 'unknown' }] },
    { t: 'boot-res', injections: [{ kind: 'script', placement: 'side', text: '' }] },
    { t: 'boot-res', injections: [{ kind: 'global', name: 1, value: null }] },
    { t: 'stream-end', id: 1 },
    { t: 'stream-item', id: 's' },
    { t: 'stream-error', id: 's' },
    { t: 'stream-cancel', id: 's', extra: true },
    { t: 'fetch-cancel', id: 1 },
    { t: 'fetch-pull', id: 1 },
    { t: 'fetch', id: 'f', url: '/', method: 'GET', headers: {}, streamBody: false },
    { t: 'open-stream', id: 's', endpoint: 1, payload: {} },
    { t: 'fetch', id: 'f', url: '/', method: 'GET', headers: { x: 1 } },
    { t: 'fetch', id: 'f', url: '/', method: 'GET', headers: {}, body: 1 },
    { t: 'fetch-res', id: 'f', status: '200', statusText: 'OK', headers: {}, body: null },
    { t: 'fetch-res', id: 'f', status: 200, statusText: 'OK', headers: {}, body: false },
    { t: 'fetch-res', id: 'f', status: 200, statusText: 'OK', headers: {}, body: null, bodyBase64: 1 },
    { t: 'fetch-res', id: 'f', status: 200, statusText: 'OK', headers: {}, body: 'x', bodyBase64: 'eA==' },
    { t: 'fetch-res', id: 'f', status: 200, statusText: 'OK', headers: {}, body: null, bodyStream: false },
    { t: 'fetch-res', id: 'f', status: 200, statusText: 'OK', headers: {}, body: 'x', bodyStream: true },
    { t: 'fetch-res', id: 'f', status: 200, statusText: 'OK', headers: {}, body: null, bodyBase64: 'eA==', bodyStream: true },
    { t: 'fetch-chunk', id: 1, bodyBase64: '' },
    { t: 'fetch-chunk', id: 'f' },
    { t: 'fetch-chunk', id: 'f', bodyBase64: 1 },
    { t: 'fetch-error', id: 1, error: 'failed' },
    { t: 'fetch-error', id: 'f' },
    { t: 'fetch-error', id: 'f', error: 1 },
    { t: 'shutdown', code: 2 },
    { t: 'shutdown', code: 0, extra: true },
    { t: 'native-request', id: 1, op: 'directory-pick' },
    { t: 'native-request', op: 'directory-pick' },
    { t: 'native-request', id: 'n', op: 'unknown-op' },
    { t: 'native-request', id: 'n', op: 'directory-pick', args: { ref: 'X' } },
    { t: 'native-request', id: 'n', op: 'credential-has' },
    { t: 'native-request', id: 'n', op: 'credential-has', args: { ref: '' } },
    { t: 'native-request', id: 'n', op: 'credential-has', args: { ref: 'X', extra: 1 } },
    { t: 'native-request', id: 'n', op: 'credential-set', args: { ref: 'X', value: '' } },
    { t: 'native-request', id: 'n', op: 'credential-set', args: { ref: 'X' } },
    { t: 'native-request', id: 'n', op: 'credential-record-list', args: { ref: 'X' } },
    {
      t: 'native-request',
      id: 'n',
      op: 'credential-record-commit',
      args: { key: 'a/b', lease: 'l', record: { kind: 'unknown' } },
    },
    {
      t: 'native-request',
      id: 'n',
      op: 'credential-record-commit',
      args: { key: 'a/b', lease: 'l', record: null },
    },
    {
      t: 'native-request',
      id: 'n',
      op: 'credential-record-commit',
      args: { key: 'a/b', lease: 'l', record: { kind: 'grant', payload: NaN } },
    },
    { t: 'native-ok', id: 'n', op: 'directory-pick' },
    { t: 'native-ok', id: 'n', op: 'directory-pick', value: 1 },
    { t: 'native-ok', id: 'n', op: 'unknown-op', value: 1 },
    { t: 'native-error', id: 'n', op: 'unknown-op', error: 'x' },
    { t: 'native-ok', id: 'n', op: 'credential-record-abort', value: null },
    { t: 'native-ok', id: 'n', op: 'credential-record-status', value: { configured: 1 } },
    { t: 'native-error', id: 'n', op: 'credential-get' },
    { t: 'native-error', id: 'n', op: 'credential-get', error: 1 },
    { t: 'native-ok', id: 'n', op: 'credential-has', value: 'yes' },
    { t: 'native-ok', id: 'n', op: 'credential-set', value: null },
    { t: 'native-ok', id: 'n', op: 'credential-record-delete', value: 'yes' },
    { t: 'native-ok', id: 'n', op: 'credential-record-read', value: { kind: 'api-key', key: '' } },
    { t: 'native-ok', id: 'n', op: 'credential-record-read', value: { kind: 'grant' } },
    { t: 'native-ok', id: 'n', op: 'credential-record-commit', value: null },
    { t: 'native-ok', id: 'n', op: 'credential-record-list', value: [{ key: '', kind: 'grant' }] },
    { t: 'native-ok', id: 'n', op: 'credential-record-list', value: [{ key: 'a/b', kind: 'other' }] },
    { t: 'native-ok', id: 'n', op: 'credential-record-lease', value: { lease: '', record: null } },
    { t: 'native-ok', id: 'n', op: 'credential-record-lease', value: { lease: 'l', record: { kind: 'nope' } } },
    { t: 'native-ok', id: 'n', op: 'credential-record-status', value: { configured: true, kind: 5 } },
    { t: 'native-request', id: 'n', op: 'directory-pick', args: 7 },
    { t: 'native-request', id: 'n', op: 'credential-has', args: { ref: 1 } },
    { t: 'native-request', id: 'n', op: 'credential-set', args: { ref: 'X', value: 1 } },
    { t: 'native-request', id: 'n', op: 'credential-record-lease', args: { key: '' } },
    { t: 'native-request', id: 'n', op: 'credential-record-abort', args: { lease: '' } },
    {
      t: 'native-request',
      id: 'n',
      op: 'credential-record-commit',
      args: { key: 'a/b', lease: '', record: { kind: 'grant', payload: {} } },
    },
    {
      t: 'native-request',
      id: 'n',
      op: 'credential-record-commit',
      args: { key: 'a/b', lease: 'l', record: { kind: 'api-key', key: '' } },
    },
    {
      t: 'native-request',
      id: 'n',
      op: 'credential-record-commit',
      args: { key: 'a/b', lease: 'l', record: { kind: 'api-key', env: 'nope' } },
    },
    {
      t: 'native-request',
      id: 'n',
      op: 'credential-record-commit',
      args: { key: 'a/b', lease: 'l', record: { kind: 'api-key', env: { '': 'v' } } },
    },
    {
      t: 'native-request',
      id: 'n',
      op: 'credential-record-commit',
      args: { key: 'a/b', lease: 'l', record: { kind: 'api-key', env: { X: '' } } },
    },
    {
      t: 'native-request',
      id: 'n',
      op: 'credential-record-commit',
      args: { key: 'a/b', lease: 'l', record: { kind: 'grant', payload: undefined } },
    },
    {
      t: 'native-request',
      id: 'n',
      op: 'credential-record-commit',
      args: cyclicGrantRecordArgs(),
    },
    {
      t: 'native-request',
      id: 'n',
      op: 'credential-record-commit',
      args: { key: 'a/b', lease: 'l', record: { kind: 'grant', payload: new Date() } },
    },
    {
      t: 'native-request',
      id: 'n',
      op: 'credential-record-commit',
      args: { key: 'a/b', lease: 'l', record: { kind: 'grant', payload: [new Date()] } },
    },
  ])('rejects malformed traffic: %j', (value) => {
    expect(parseDesktopIpcMessage(value)).toBeUndefined()
  })
})
